apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles
  namespace: default
  labels:
    app: candles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candles
  template:
    metadata:
      labels:
        app: candles
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: candles
          image: candles:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: KAFKA_BROKER_ADDRESS
              value: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: KAFKA_INPUT_TOPIC
              value: "trades"
            - name: KAFKA_OUTPUT_TOPIC
              value: "candles"
            - name: KAFKA_CONSUMER_GROUP
              value: "candles-consumer-group"
            - name: CANDLE_SECONDS
              value: "60"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
