apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-indicators
  namespace: default
  labels:
    app: technical-indicators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technical-indicators
  template:
    metadata:
      labels:
        app: technical-indicators
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: technical-indicators
          image: technical-indicators:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: KAFKA_BROKER_ADDRESS
              value: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: KAFKA_INPUT_TOPIC
              value: "candles"
            - name: KAFKA_OUTPUT_TOPIC
              value: "technical_indicators"
            - name: KAFKA_CONSUMER_GROUP
              value: "technical-indicators-consumer-group"
            - name: CANDLE_SECONDS
              value: "60"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
