apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  namespace: default
  labels:
    app: trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      containers:
        - name: trades
          image: trades:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BROKER_ADDRESS
              value: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: KAFKA_TOPIC_NAME
              value: "trades"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
